steps:
  - name: Install Profile Drupal with Plugin Demo
  - name: Run the profile script
    command: './$SRC_DIR/.probo-profile-build.sh'

    plugin: Drupal
    installArgs: "--site-name='Install Profile Drupal Plugin Demo'"
    clearCaches: true
    profileName: bear
    runInstall: true

  - name: Set file directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
